# Generated by Django 4.1 on 2022-09-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windirmember',
            name='days',
        ),
    ]
