# Generated by Django 4.1 on 2022-09-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0003_windirmember_arma_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windirmember',
            old_name='telegram_username',
            new_name='telegramUsername',
        ),
    ]
