# Generated by Django 4.1 on 2022-09-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0004_rename_telegram_username_windirmember_telegramusername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windirmember',
            name='approved',
        ),
        migrations.AlterField(
            model_name='windirmember',
            name='arma_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='windirmember',
            name='telegramUsername',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='windirmember',
            name='utc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
