# Generated by Django 4.1 on 2022-09-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0005_remove_windirmember_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='windirmember',
            old_name='arma_hours',
            new_name='hours',
        ),
        migrations.RemoveField(
            model_name='windirmember',
            name='telegramUsername',
        ),
        migrations.AddField(
            model_name='windirmember',
            name='contact',
            field=models.CharField(default='meow', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='windirmember',
            name='other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='windirmember',
            name='teams',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='windirmember',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windir.project'),
        ),
        migrations.AddField(
            model_name='windirmember',
            name='specs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windir.spec'),
        ),
    ]
