# Generated by Django 4.1 on 2022-09-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0006_project_spec_rename_arma_hours_windirmember_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windirmember',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='windirmember',
            name='specs',
        ),
        migrations.AddField(
            model_name='windirmember',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='windir.project'),
        ),
        migrations.AddField(
            model_name='windirmember',
            name='specs',
            field=models.ManyToManyField(blank=True, null=True, to='windir.spec'),
        ),
    ]
