# Generated by Django 4.1 on 2022-09-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0007_remove_windirmember_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windirmember',
            name='projects',
            field=models.ManyToManyField(to='windir.project'),
        ),
        migrations.AlterField(
            model_name='windirmember',
            name='specs',
            field=models.ManyToManyField(to='windir.spec'),
        ),
    ]
