# Generated by Django 4.1 on 2022-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0010_alter_windirmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windirmember',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
