# Generated by Django 4.1 on 2022-09-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0011_windirmember_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='windirmember',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
