# Generated by Django 4.1 on 2022-09-16 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0013_windirmember_groups_windirmember_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='project-imgs/'),
        ),
        migrations.AlterField(
            model_name='windirmember',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('first', models.ManyToManyField(related_name='game_first', to=settings.AUTH_USER_MODEL)),
                ('project', models.ManyToManyField(to='windir.project')),
                ('second', models.ManyToManyField(related_name='game_second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
