# Generated by Django 4.1 on 2022-09-16 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0015_game_weekday_alter_game_first_alter_game_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='project',
        ),
        migrations.AddField(
            model_name='game',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='windir.project'),
            preserve_default=False,
        ),
    ]
