# Generated by Django 4.1 on 2022-09-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0019_alter_game_options_alter_game_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='weekday',
        ),
    ]
