# Generated by Django 4.1 on 2022-09-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0020_remove_game_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='weekday',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
