# Generated by Django 4.1 on 2022-09-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0021_game_weekday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['weekday']},
        ),
        migrations.AlterField(
            model_name='game',
            name='weekday',
            field=models.IntegerField(unique=True),
        ),
    ]
