# Generated by Django 4.1 on 2022-09-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0022_alter_game_options_alter_game_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windirmember',
            old_name='projects',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='windirmember',
            old_name='specs',
            new_name='spec',
        ),
    ]
