# Generated by Django 4.1 on 2022-09-27 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windir', '0024_alter_windirmember_utc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='weekday',
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 8, 1, 56, 61869, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
